apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsc-api
  labels:
    app: gsc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gsc-api
  template:
    metadata:
      labels:
        app: gsc-api
    spec:
      containers:
      - name: gsc-api
        image: poliakarmai/gsc:0.38
        command: ["gsc","api","--port","8766"]
        ports:
        - containerPort: 8766
        env:
        - name: GSC_DB_TYPE
          value: "postgres"
        - name: GSC_DB_HOST
          value: "gsc-postgres"
        - name: GSC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gsc-db-credentials
              key: password
        - name: GSC_SSO_ISSUER
          valueFrom:
            secretKeyRef:
              name: gsc-sso-credentials
              key: issuerUrl
        resources:
          limits: {cpu: "2", memory: "2Gi"}
          requests: {cpu: "500m", memory: "512Mi"}
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8766
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8766
          initialDelaySeconds: 5
