apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: gsc-api
    app.kubernetes.io/name: gsc-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  selector:
    app: gsc-api
  ports:
  - name: http
    port: 8001
    targetPort: http
    protocol: TCP
