#!/usr/bin/env python3
"""Tests for multilang sandbox runners (JavaScript/Node path).

The Go/Java/Rust runners are generated by gsc_multilang_runners (tested in
test_gsc_multilang_runners.py); here we verify the sandbox integration for the
one non-Python runtime that is guaranteed-ish on CI (node). Tests skip when
node is absent.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from gsc_pof_sandbox import PoFSandbox, verify_pof  # noqa: E402

_JS_VULN = '''function checkPassword(pw) {
  if (pw === "admin123") return "secret-data-here";
  return "denied";
}
module.exports = { checkPassword };
'''

_JS_PATCHED = '''function checkPassword(pw) {
  if (pw === process.env.ADMIN_PW) return "secret-data-here";
  return "denied";
}
module.exports = { checkPassword };
'''

_JS_POC = '''const t = require("./target");
if (t.checkPassword("admin123") === "secret-data-here") { console.log("EXPLOITED: weak password"); }
'''

requires_node = pytest.mark.skipif(shutil.which("node") is None,
                                   reason="node runtime not available")


@requires_node
def test_javascript_poc_triggers_before_not_after() -> None:
    """PoC triggers on vulnerable JS, is silent on patched JS."""
    sb = PoFSandbox()
    before = sb._execute_multilang(_JS_POC, _JS_VULN, "javascript")
    assert before.success is True, f"stderr={before.stderr}"
    assert "EXPLOITED" in before.stdout

    after = sb._execute_multilang(_JS_POC, _JS_PATCHED, "javascript")
    assert after.success is False


@requires_node
def test_verify_fix_javascript_reports_rlimit_isolation() -> None:
    """verify_fix runs the full before/after cycle and stays fail-closed on rlimit."""
    finding = {"rule_id": "GS017", "severity": "HIGH",
               "metadata": {"poc_format": "javascript"}}
    r = verify_pof(finding, _JS_VULN, _JS_PATCHED, _JS_POC, language="javascript")
    assert r.before.success is True
    assert r.after.success is False
    # fail-closed: rlimit is not OS-isolation, so verified must stay False
    assert r.verified is False
    assert "container runtime" in r.reason


def test_unsupported_language_returns_error() -> None:
    """An unknown language yields a clean error, not a crash."""
    sb = PoFSandbox()
    r = sb._execute_multilang("x", "y", "cobol")
    assert r.success is False
    assert r.error
