# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Алексей Поляков
# Licensed under Apache License 2.0 — see LICENSE

"""Tests for the Rust Cargo.lock PoF parser (Phase 14)."""

from gsc_cli.gsc_pof_cargo_lock_parser import (
    CargoLockPackage,
    CargoLockProject,
    detect_cargo_lock_project,
    parse_cargo_lock,
)


def _sample() -> str:
    return (
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 3\n"
        "\n"
        "[[package]]\n"
        'name = "myapp"\n'
        'version = "0.1.0"\n'
        "dependencies = [\n"
        ' "serde",\n'
        ' "tokio",\n'
        "]\n"
        "\n"
        "[[package]]\n"
        'name = "serde"\n'
        'version = "1.0.188"\n'
        'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
        'checksum = "e71a..."\n'
    )


# ── detect_cargo_lock_project ───────────────────────────────────────────


def test_detect_empty_list():
    assert detect_cargo_lock_project([]) is False


def test_detect_cargo_lock():
    assert detect_cargo_lock_project(["Cargo.lock", "src/lib.rs"]) is True


def test_detect_nested_path():
    assert detect_cargo_lock_project(["src/Cargo.lock"]) is True


def test_detect_case_insensitive():
    assert detect_cargo_lock_project(["CARGO.LOCK"]) is True


def test_detect_not_cargo_lock():
    assert detect_cargo_lock_project(["Cargo.toml"]) is False


# ── parse_cargo_lock ────────────────────────────────────────────────────


def test_parse_valid_sample():
    p = parse_cargo_lock(_sample())
    assert p.valid is True
    assert p.lock_version == "3"
    assert len(p.packages) == 2
    assert p.packages[0].name == "myapp"
    assert p.packages[0].version == "0.1.0"
    assert p.packages[0].dependencies == ["serde", "tokio"]
    assert p.packages[0].source == ""
    assert p.packages[1].name == "serde"
    assert p.packages[1].version == "1.0.188"
    assert p.packages[1].source == "registry+https://github.com/rust-lang/crates.io-index"


def test_parse_multiple_packages():
    content = (
        "version = 3\n\n"
        "[[package]]\nname = \"a\"\nversion = \"1.0.0\"\n\n"
        "[[package]]\nname = \"b\"\nversion = \"2.0.0\"\n"
    )
    p = parse_cargo_lock(content)
    assert p.valid is True
    assert [x.name for x in p.packages] == ["a", "b"]


def test_parse_package_without_source():
    p = parse_cargo_lock('version = 3\n\n[[package]]\nname = "x"\nversion = "1.0.0"\n')
    assert p.valid is True
    assert p.packages[0].source == ""


def test_parse_empty_string():
    assert parse_cargo_lock("").valid is False


def test_parse_none():
    assert parse_cargo_lock(None).valid is False


def test_parse_non_string():
    assert parse_cargo_lock(123).valid is False


def test_parse_no_package_table():
    p = parse_cargo_lock('version = 3\n\n[metadata]\nfoo = "bar"\n')
    assert p.valid is False


def test_parse_checksum_not_exposed():
    p = parse_cargo_lock(_sample())
    d = p.packages[1].to_dict()
    assert "checksum" not in d
    assert "source" in d


# ── to_dict / require_for ───────────────────────────────────────────────


def test_to_dict_shape():
    p = parse_cargo_lock(_sample())
    d = p.to_dict()
    assert d["valid"] is True
    assert d["lock_version"] == "3"
    assert len(d["packages"]) == 2
    assert d["packages"][0]["name"] == "myapp"
    assert d["packages"][0]["dependencies"] == ["serde", "tokio"]


def test_require_for_finds_package():
    p = parse_cargo_lock(_sample())
    found = p.require_for("serde")
    assert found is not None
    assert found.version == "1.0.188"


def test_require_for_returns_none_when_absent():
    p = parse_cargo_lock(_sample())
    assert p.require_for("nope") is None
    assert p.require_for("") is None
