# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Алексей Поляков
# Licensed under Apache License 2.0 — see LICENSE

"""Rust Cargo.lock PoF Parser (Phase 14 — PoF multilingualism: Rust).

Pure, side-effect-free helpers used by the Proof-of-Fix pipeline to recognize
a Rust project's `Cargo.lock` file and extract the minimal manifest slice
it needs:

  * ``detect_cargo_lock_project(files)`` — presence check of ``Cargo.lock``
    in a file list (case-insensitive, basename only).
  * ``parse_cargo_lock(content)`` — line-based parser that extracts the
    ``lock_version`` and every ``[[package]]`` table's ``name``, ``version``,
    ``dependencies`` (list of names), and ``source``.
    Checksums are ignored.

Design notes
------------
* No filesystem access, no environment variables, no I/O. Functions take
  strings / lists and return dataclasses — fully unit-testable in isolation.
* The parser is best-effort: malformed input yields a
  ``CargoLockProject(valid=False)`` with empty fields rather than raising. The
  PoF orchestrator can then skip Rust-specific fix strategies without
  catching exceptions.
* Stdlib only (``re``). Intentionally NOT using ``tomllib`` (Python 3.11+)
  or ``tomli`` — CI still runs Python 3.10. Cargo.lock is a TOML-like
  document but we only need a thin slice, so a regex-based scan is
  sufficient and keeps the dependency surface at zero.
* Backward-compatibility: this is a new module (Phase 14), no aliases needed.

Cargo.lock grammar (relevant subset)
------------------------------------
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = [
 "serde",
 "tokio",
]

[[package]]
name = "serde"
version = "1.0.188"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "e71a..."

Other sections (``[metadata]``, ``[[patch]]``) are ignored.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable


_CARGO_LOCK_BASENAME = "Cargo.lock"

_PACKAGE_SECTION_RE = re.compile(r"^\s*\[\[package\]\]\s*$")
_SECTION_RE = re.compile(r"^\s*\[([^\]]+)\]\s*$") # For any other section type
_SIMPLE_KV_RE = re.compile(r"^\s*([A-Za-z0-9_\-]+)\s*=\s*\"([^\"\n]*)\"$")
_DEPENDENCIES_START_RE = re.compile(r"^\s*dependencies\s*=\s*\[")
_DEPENDENCY_NAME_RE = re.compile(r'\"([A-Za-z0-9_\-]+)\"')
# Cargo.lock writes the lockfile format version as an unquoted integer
# (``version = 3``), unlike package names/versions which are quoted.
_LOCK_VERSION_RE = re.compile(r"^\s*version\s*=\s*(\d+)\s*$")


@dataclass
class CargoLockPackage:
    """A single ``[[package]]`` table extracted from ``Cargo.lock``.

    ``name`` is the package name; ``version`` is the resolved version string.
    ``dependencies`` is a list of package names that this package depends on.
    ``source`` is the registry or git URL, or an empty string if not present.
    """

    name: str
    version: str = ""
    dependencies: list[str] = field(default_factory=list)
    source: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "version": self.version,
            "dependencies": self.dependencies,
            "source": self.source,
        }


@dataclass
class CargoLockProject:
    """A best-effort, tolerant view of a Rust ``Cargo.lock`` file.

    All fields are optional / may be empty. ``valid`` is False when the
    input was empty / non-string / contained no ``[[package]]`` table
    with a non-empty ``name`` — the PoF orchestrator can use that flag to
    skip Rust-specific fix strategies without surfacing a hard error.
    """

    valid: bool = False
    lock_version: str = ""
    packages: list[CargoLockPackage] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "valid": self.valid,
            "lock_version": self.lock_version,
            "packages": [p.to_dict() for p in self.packages],
        }

    def require_for(self, name: str) -> CargoLockPackage | None:
        """Return the first CargoLockPackage with the given package name.

        Searches the full ``packages`` list in declaration order (which
        mirrors the order in ``Cargo.lock``) so callers can rely on the
        "first match wins" semantics consistent with the other PoF
        language parsers.
        """

        for p in self.packages:
            if p.name == name:
                return p
        return None


# ── Public API ───────────────────────────────────────────────────────────


def detect_cargo_lock_project(files: Iterable[str]) -> bool:
    """Return True if any of ``files`` is a ``Cargo.lock``.

    ``files`` may be absolute or relative paths; only the basename is
    inspected. Comparison is case-insensitive to match Windows / macOS
    filesystems where ``CARGO.LOCK`` or ``Cargo.Lock`` would otherwise be
    invisible.
    """
    if not files:
        return False
    target = _CARGO_LOCK_BASENAME.lower()
    for f in files:
        if not isinstance(f, str):
            continue
        # os.path.basename is avoided to keep the helper purely functional
        # and free of filesystem semantics; split on both / and \ so we
        # work on POSIX and Windows-style paths.
        base = f.rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
        if base.lower() == target:
            return True
    return False


def parse_cargo_lock(content: str) -> CargoLockProject:
    """Parse a ``Cargo.lock`` string into a ``CargoLockProject``.

    Tolerant: empty input, non-string input, and Cargo.lock files without
    a single ``[[package]]`` table with a ``name`` field all yield
    ``CargoLockProject(valid=False)`` with empty fields rather than raising.
    ``#`` line comments are stripped before parsing so annotated values
    are handled correctly. Multi-line inline arrays (e.g.
    ``dependencies = [ ... ]``) are joined into a single logical line so the
    outer key/value scanner doesn't drift out of section.
    """
    if not isinstance(content, str) or not content.strip():
        return CargoLockProject(valid=False)

    cleaned = _strip_comments(content)
    logical = _logical_lines(cleaned)

    lock_version = _parse_lock_version(logical)
    packages = _parse_packages(logical)

    if not any(p.name for p in packages):
        return CargoLockProject(valid=False, lock_version=lock_version)

    return CargoLockProject(
        valid=True,
        lock_version=lock_version,
        packages=packages,
    )


# ── Internal helpers ─────────────────────────────────────────────────────


def _strip_comments(content: str) -> str:
    """Remove ``#`` line comments from a Cargo.lock string.

    Cargo only allows ``#`` line comments (no ``/* */`` block comments),
    so a single regex pass is sufficient. Comments may appear on their
    own line or after a value; both forms are stripped.
    """
    return re.sub(r"#[^\n]*", "", content)


def _logical_lines(content: str) -> list[str]:
    """Join continuation lines into single logical lines.

    Cargo.lock allows arrays to span multiple lines, e.g.::

        dependencies = [
         "serde",
         "tokio",
        ]

    For our simple parser we need to handle this to correctly identify
    the `dependencies` block. When an opening ``[`` on a line is not
    balanced by a closing ``]`` on the same line, we keep appending
    the next physical line until balance is restored.
    """
    out: list[str] = []
    buf: list[str] = []
    depth = 0
    for raw in content.splitlines():
        if not buf:
            # Fast path: balanced on this line — no continuation.
            opens = raw.count("[")
            closes = raw.count("]")
            if opens == closes:
                out.append(raw)
                continue
            buf.append(raw)
            depth = opens - closes
            continue
        buf.append(raw)
        depth += raw.count("[") - raw.count("]")
        if depth <= 0:
            out.append(" ".join(buf))
            buf = []
            depth = 0
    if buf:
        out.append(" ".join(buf))
    return out


def _parse_lock_version(logical_lines: list[str]) -> str:
    """Extract the top-level ``version`` value."""
    for line in logical_lines:
        stripped = line.strip()
        if not stripped:
            continue
        # Any section header closes the top-level window.
        if _PACKAGE_SECTION_RE.match(stripped) or _SECTION_RE.match(stripped):
            break
        m = _SIMPLE_KV_RE.match(stripped)
        if m:
            key, value = m.group(1), m.group(2).strip()
            if key == "version":
                return value
        nm = _LOCK_VERSION_RE.match(stripped)
        if nm:
            return nm.group(1)
    return ""


def _parse_packages(logical_lines: list[str]) -> list[CargoLockPackage]:
    """Extract every ``[[package]]`` table as a ``CargoLockPackage``."""
    packages: list[CargoLockPackage] = []
    in_package = False
    current_name = ""
    current_version = ""
    current_dependencies: list[str] = []
    current_source = ""

    for line in logical_lines:
        stripped = line.strip()
        if not stripped:
            continue

        pkg_match = _PACKAGE_SECTION_RE.match(stripped)
        if pkg_match:
            if in_package:
                packages.append(
                    CargoLockPackage(
                        name=current_name,
                        version=current_version,
                        dependencies=current_dependencies,
                        source=current_source,
                    )
                )
            in_package = True
            current_name = ""
            current_version = ""
            current_dependencies = []
            current_source = ""
            continue

        if _SECTION_RE.match(stripped):
            if in_package:
                packages.append(
                    CargoLockPackage(
                        name=current_name,
                        version=current_version,
                        dependencies=current_dependencies,
                        source=current_source,
                    )
                )
            in_package = False
            current_name = ""
            current_version = ""
            current_dependencies = []
            current_source = ""
            continue

        if not in_package:
            continue

        # Check for dependencies = [ "a", "b" ]
        if _DEPENDENCIES_START_RE.match(stripped):
            dep_names = _DEPENDENCY_NAME_RE.findall(stripped)
            current_dependencies.extend(dep_names)
            continue

        m = _SIMPLE_KV_RE.match(stripped)
        if not m:
            continue
        key, value = m.group(1), m.group(2).strip()
        if key == "name" and not current_name:
            current_name = value
        elif key == "version" and not current_version:
            current_version = value
        elif key == "source" and not current_source:
            current_source = value

    if in_package:
        packages.append(
            CargoLockPackage(
                name=current_name,
                version=current_version,
                dependencies=current_dependencies,
                source=current_source,
            )
        )

    return packages
