# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Алексей Поляков
# Licensed under Apache License 2.0 — see LICENSE

"""Yarn v1 (classic) PoF Project Parser (Phase 14 — PoF multilingualism: Yarn).

Pure, side-effect-free helpers used by the Proof-of-Fix pipeline to recognize
a Yarn v1 project and extract the minimal lockfile slice it needs:

  * ``detect_yarn_project(files)`` — presence check of ``yarn.lock`` in a
    file list (case-insensitive, basename only).
  * ``parse_yarn_lock(content)``   — line-based parser that extracts every
    ``name@range`` entry along with its resolved ``version`` and ``resolved``
    URL from a ``yarn.lock`` v1 lockfile.

Design notes
------------
* No filesystem access, no environment variables, no I/O. Functions take
  strings / lists and return dataclasses — fully unit-testable in isolation.
* The parser is best-effort: malformed input yields a
  ``YarnProject(valid=False)`` with an empty package list rather than
  raising. The PoF orchestrator can then skip Yarn-specific fix strategies
  without catching exceptions.
* Stdlib only (``re``, ``dataclasses``, ``typing``). Intentionally NOT using
  any third-party lockfile parser — CI runs offline and the format is small
  enough for a line-based scan to be reliable.
* Backward-compatibility: this is a new module (Phase 14), no aliases needed.

yarn.lock v1 grammar (relevant subset)
--------------------------------------
::

    # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    # yarn lockfile v1


    lodash@^4.17.20, lodash@^4.17.21:
      version "4.17.21"
      resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
      integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==

    "@babel/code-frame@^7.0.0":
      version "7.22.13"
      resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz"
      integrity sha512-...

Keys may be unquoted (``lodash@^4.17.20``) or quoted (``"@babel/code-frame@^7.0.0"``)
and may declare several ranges separated by ``,``. Each value line is
indented (2 spaces) and has the shape ``field "value"`` (other fields like
``integrity`` are ignored — only ``version`` and ``resolved`` are exposed
because they drive the SCA fix strategy).
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Iterable

# A file is considered a yarn.lock candidate when its basename is exactly
# "yarn.lock" (case-insensitive). The PoF pipeline is run on already-walked
# file lists, so we don't try to guess paths here.
_YARN_LOCK_BASENAME = "yarn.lock"

# Matches an entry key line that ends in ``:`` after optional whitespace.
# The whole body from the start of the line up to (but not including) the
# trailing colon is captured as group 1; we will post-process it to peel
# off surrounding quotes, drop any comma-separated sibling variants, and
# split on the LAST ``@`` to separate name from version range. A leading
# ``#`` comment line is intentionally NOT matched here — it never ends
# in ``:`` so it falls through the block parser.
_ENTRY_KEY_RE = re.compile(r'^\s*(.+?):\s*$')

# Matches a ``field "value"`` line under an entry block. Captures the field
# name and the quoted value. Anchored at the start so we don't accidentally
# pick up ``integrity`` substrings (it is also ``field "..."``) — we only
# look for the specific fields the orchestrator needs.
_FIELD_RE = re.compile(r'^\s{2,}([A-Za-z][A-Za-z0-9_-]*)\s+"([^"\n]*)"')

# Fields we extract from a yarn.lock entry body. Others (integrity, etc.)
# are read but discarded — they don't drive any PoF decision today.
_VERSION_FIELDS = ("version",)
_RESOLVED_FIELDS = ("resolved",)


@dataclass
class YarnPackage:
    """A single resolved package extracted from ``yarn.lock``.

    ``name`` is the package name as it appears in the entry key (scoped
    names keep their ``@scope/`` prefix); ``version`` is the resolved
    semver string from the ``version "..."`` line; ``resolved`` is the
    tarball URL from the ``resolved "..."`` line. Both ``version`` and
    ``resolved`` may be empty when the corresponding line is missing —
    the dataclass stays useful as a "package exists" marker in that
    case.
    """

    name: str
    version: str = ""
    resolved: str = ""

    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "version": self.version,
            "resolved": self.resolved,
        }


@dataclass
class YarnProject:
    """A best-effort, parser-tolerant view of a ``yarn.lock`` v1 file.

    All fields are optional / may be empty. ``valid`` is False when the
    input was empty / non-string / contained no recognisable entry with a
    non-empty ``name`` — the PoF orchestrator can use that flag to skip
    Yarn-specific fix strategies without surfacing a hard error.
    """

    valid: bool = False
    packages: list[YarnPackage] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "valid": self.valid,
            "packages": [p.to_dict() for p in self.packages],
        }

    def require_for(self, name: str) -> YarnPackage | None:
        """Return the first YarnPackage with the given name, or None.

        Scoped names match exactly (including their leading ``@``), so
        ``require_for("@babel/code-frame")`` will not accidentally hit
        ``"babel-code-frame"``.
        """
        for p in self.packages:
            if p.name == name:
                return p
        return None


# ── Public API ───────────────────────────────────────────────────────────


def detect_yarn_project(files: Iterable[str]) -> bool:
    """Return True if any of ``files`` is a ``yarn.lock``.

    ``files`` may be absolute or relative paths; only the basename is
    inspected. Comparison is case-insensitive to match Windows / macOS
    filesystems where ``YARN.LOCK`` would otherwise be invisible.
    """
    if not files:
        return False
    target = _YARN_LOCK_BASENAME.lower()
    for f in files:
        if not isinstance(f, str):
            continue
        # os.path.basename is avoided to keep the helper purely functional
        # and free of filesystem semantics; split on both / and \ so we
        # work on POSIX and Windows-style paths.
        base = f.rsplit("/", 1)[-1].rsplit("\\", 1)[-1]
        if base.lower() == target:
            return True
    return False


def parse_yarn_lock(content: str) -> YarnProject:
    """Parse a ``yarn.lock`` v1 string into a ``YarnProject``.

    Tolerant: empty input, non-string input, files that contain only
    comments, and files with no entry lines all yield
    ``YarnProject(valid=False)`` rather than raising. The PoF orchestrator
    can then decide to skip the Yarn-specific strategy without catching
    exceptions.
    """
    if not isinstance(content, str) or not content.strip():
        return YarnProject(valid=False)

    packages = _parse_entries(content)
    if not packages:
        return YarnProject(valid=False)

    return YarnProject(valid=True, packages=packages)


# ── Internal helpers ─────────────────────────────────────────────────────


def _parse_entries(content: str) -> list[YarnPackage]:
    """Walk the lockfile once and collect one YarnPackage per entry.

    We split the content into two kinds of lines: entry keys (ending in
    ``:``) and value lines (indented ``field "value"``). The block parser
    is intentionally stateless across entries — each new key resets the
    field accumulator, and we only emit a package once we have a key
    line, regardless of whether the block had any value lines at all
    (a key with no fields still produces a YarnPackage with empty
    version/resolved, which downstream can treat as a "we saw the name"
    signal).
    """
    packages: list[YarnPackage] = []
    current_name = ""
    current_version = ""
    current_resolved = ""

    for raw in content.splitlines():
        # Strip a trailing inline comment ("  # foo") only outside of
        # quoted strings — yarn.lock doesn't allow "#" inside quoted
        # values, so a simple find("#") at column 2+ is safe here.
        line = raw
        # Skip whole-line comments up front: they can never be an entry
        # key (they don't end in ":") and we don't want to mistake an
        # indented "  # something" for a field line.
        if line.lstrip().startswith("#"):
            continue
        # Drop an inline trailing comment, if any. The "#" is preceded
        # by at least one space by yarn.lock convention.
        hash_idx = _find_inline_comment(line)
        if hash_idx >= 0:
            line = line[:hash_idx].rstrip()

        if not line.strip():
            # Blank line: end the current entry (if any) and reset.
            if current_name:
                packages.append(
                    YarnPackage(
                        name=current_name,
                        version=current_version,
                        resolved=current_resolved,
                    )
                )
                current_name = ""
                current_version = ""
                current_resolved = ""
            continue

        m = _ENTRY_KEY_RE.match(line)
        if m:
            # Flush the previous entry first so two consecutive key
            # lines (no blank between) still produce both packages.
            if current_name:
                packages.append(
                    YarnPackage(
                        name=current_name,
                        version=current_version,
                        resolved=current_resolved,
                    )
                )
                current_name = ""
                current_version = ""
                current_resolved = ""
            key_body = m.group(1).strip()
            new_name = _name_from_key(key_body)
            # A key without a usable ``@`` separator is not a package
            # entry — e.g. an accidentally-matched stray "something:"
            # in some non-standard input. Ignore it so the previously
            # accumulated version/resolved aren't silently re-parented
            # to an empty name.
            if new_name:
                current_name = new_name
            continue

        # Indented "field \"value\"" line. Only act on lines that look
        # like a field declaration under the current entry; otherwise
        # leave the parser quiet and continue.
        if not line.startswith((" ", "\t")):
            continue
        fm = _FIELD_RE.match(line)
        if not fm:
            continue
        field_name = fm.group(1)
        field_value = fm.group(2)
        if field_name in _VERSION_FIELDS and not current_version:
            current_version = field_value
        elif field_name in _RESOLVED_FIELDS and not current_resolved:
            current_resolved = field_value

    # Flush the last entry if the file does not end with a blank line.
    if current_name:
        packages.append(
            YarnPackage(
                name=current_name,
                version=current_version,
                resolved=current_resolved,
            )
        )

    return packages


def _name_from_key(key_body: str) -> str:
    """Extract the canonical package name from a yarn.lock entry key body.

    The body is the raw text between the optional opening quote and the
    trailing colon. We:

      1. Drop any trailing comma+space (the common form is
         ``name@range, name@other-range`` — we keep just the first).
      2. Strip any surrounding quotes around the first variant.
      3. Split on the LAST ``@`` so scoped names (``@scope/name``) keep
         their leading ``@`` together with the slash segment.

    Returns ``""`` if the body has no ``@`` at all (e.g. a malformed key)
    or after stripping the range part nothing meaningful remains.
    """
    if not key_body:
        return ""

    body = key_body.strip()

    # A quoted key wraps the ENTIRE comma-separated variant list, e.g.
    #   "@babel/code-frame@^7.0.0, @babel/code-frame@^7.10.4"
    # so the closing quote sits only after the LAST variant. Peel the
    # outer pair off the whole body first.
    if len(body) >= 2 and body[0] == '"' and body[-1] == '"':
        body = body[1:-1]

    # Take only the first variant, in case several are comma-separated.
    first = body.split(",", 1)[0].strip()

    # A per-variant quote pair (e.g. "\"chalk@^2.0.0\", chalk@^2.4.2")
    # leaves a quoted first variant after the split — peel it too.
    if len(first) >= 2 and first[0] == '"' and first[-1] == '"':
        first = first[1:-1]

    if not first:
        return ""

    # Split on the LAST "@" so "@scope/name@1" -> ("@scope/name", "1").
    at_idx = first.rfind("@")
    if at_idx <= 0:
        # No "@" or "@" is the very first character with no name on its
        # left — neither is a valid yarn entry.
        return ""
    name = first[:at_idx].strip()
    return name


def _find_inline_comment(line: str) -> int:
    """Return the index of an inline ``#`` comment, or ``-1`` if none.

    We require the ``#`` to be preceded by whitespace so we don't
    accidentally split out a ``#`` that is part of a value (yarn.lock
    does not use ``#`` inside quoted values, but the comment marker is
    always preceded by at least one space in practice).
    """
    idx = 0
    while idx < len(line):
        ch = line[idx]
        if ch == "#":
            if idx == 0 or line[idx - 1] in (" ", "\t"):
                return idx
            return -1
        if ch == '"':
            # Skip a quoted span so an embedded "#" doesn't trip us.
            idx += 1
            while idx < len(line) and line[idx] != '"':
                idx += 1
            # idx is now on the closing quote (or past the end) — the
            # outer loop will advance one more and resume scanning.
        idx += 1
    return -1
