# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Алексей Поляков
# Licensed under Apache License 2.0 — see LICENSE

"""GSC PoC watermarking — dual-use mitigation.

Every generated proof-of-concept gets a visible "authorized security testing
only" banner plus a stable, trackable PoC ID (sha256 fingerprint). The ID is
derived from the finding identity (rule, file, line, finding_key) — NOT from
the code — so a given finding always maps to the same ID, and a leaked PoC
can be traced back to its source finding.

Watermarking is idempotent: re-running it over an already-watermarked PoC is
a no-op, so it is safe to call from multiple attach paths.
"""

from __future__ import annotations

import hashlib

_WATERMARK_MARKER = "GSC PROOF-OF-CONCEPT — AUTHORIZED SECURITY TESTING ONLY"


def compute_poc_id(finding: dict) -> str:
    """Stable, trackable fingerprint for a PoC (12 hex chars)."""
    key = "|".join(
        str(finding.get(k, ""))
        for k in ("rule_id", "file_path", "line", "finding_key")
    )
    return hashlib.sha256(key.encode("utf-8")).hexdigest()[:12]


def watermark_poc(code: str, finding: dict, poc_id: str) -> str:
    """Embed a visible banner + PoC ID into PoC code (idempotent).

    Uses ``#`` comments, valid across the supported PoC formats (curl/bash,
    python, pytest).
    """
    if _WATERMARK_MARKER in code:
        return code  # already watermarked

    rule = finding.get("rule_id") or finding.get("pattern_title") or "?"
    file = finding.get("file_path") or finding.get("file") or "?"
    line = finding.get("line") or finding.get("line_number") or "?"
    banner = (
        "# " + "=" * 77 + "\n"
        f"# {_WATERMARK_MARKER}\n"
        "# Generated by Git Security Checker (gsc)\n"
        f"# Rule: {rule} | File: {file}:{line}\n"
        f"# PoC ID: {poc_id}\n"
        "# Unauthorized use prohibited. Authorized pentests / responsible disclosure only.\n"
        "# " + "=" * 77 + "\n"
    )
    return banner + code


def watermark_findings(findings: list[dict]) -> list[dict]:
    """Attach a watermark to every finding that carries a PoC. Mutates in-place."""
    for f in findings:
        poc = f.get("metadata", {}).get("poc")
        if not poc or not isinstance(poc, str):
            continue
        poc_id = compute_poc_id(f)
        f.setdefault("metadata", {})
        f["metadata"]["poc_watermark_id"] = poc_id
        f["metadata"]["poc_watermark"] = True
        f["metadata"]["poc"] = watermark_poc(poc, f, poc_id)
    return findings
