#!/usr/bin/env python3
"""GSC Report — HTML/PDF export of findings."""
import sys, os, sqlite3, json
from datetime import datetime

DB = os.path.expanduser("~/.hermes/state/gsc_audit.db")

def export_html(project: str = None, output: str = None):
    if not os.path.exists(DB):
        print("No database"); return

    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row

    where = f"WHERE project = '{project}'" if project else "WHERE 1=1"
    total = conn.execute(f"SELECT COUNT(*) FROM findings {where}").fetchone()[0]
    crit = conn.execute(f"SELECT COUNT(*) FROM findings {where} AND category='CRITICAL'").fetchone()[0]
    high = conn.execute(f"SELECT COUNT(*) FROM findings {where} AND category='HIGH'").fetchone()[0]
    medium = conn.execute(f"SELECT COUNT(*) FROM findings {where} AND category='MEDIUM'").fetchone()[0]
    findings = conn.execute(f"SELECT * FROM findings {where} ORDER BY CASE category WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END, id LIMIT 50").fetchall()
    conn.close()

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>GSC Audit Report{' — ' + project if project else ''}</title>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; background: #f8f9fa; }}
  h1 {{ border-bottom: 3px solid #6c5ce7; padding-bottom: 10px; }}
  .summary {{ display: flex; gap: 20px; margin: 20px 0; }}
  .card {{ background: white; border-radius: 8px; padding: 16px 24px; box-shadow: 0 1px 3px rgba(0,0,0,.1); flex: 1; text-align: center; }}
  .card .num {{ font-size: 32px; font-weight: 700; }}
  .CRITICAL .num {{ color: #e74c3c; }} .HIGH .num {{ color: #e67e22; }} .MEDIUM .num {{ color: #f39c12; }} .TOTAL .num {{ color: #6c5ce7; }}
  .finding {{ background: white; border-radius: 8px; padding: 12px 16px; margin: 8px 0; box-shadow: 0 1px 2px rgba(0,0,0,.05); border-left: 4px solid #ddd; }}
  .CRITICAL.finding {{ border-left-color: #e74c3c; }} .HIGH.finding {{ border-left-color: #e67e22; }} .MEDIUM.finding {{ border-left-color: #f39c12; }}
  .finding .title {{ font-weight: 600; }} .finding .meta {{ font-size: 13px; color: #888; margin-top: 4px; }}
  .finding .detail {{ font-size: 14px; color: #555; margin-top: 6px; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; color: white; }}
  .badge-CRITICAL {{ background: #e74c3c; }} .badge-HIGH {{ background: #e67e22; }} .badge-MEDIUM {{ background: #f39c12; }} .badge-LOW {{ background: #27ae60; }}
  footer {{ margin-top: 40px; text-align: center; font-size: 12px; color: #aaa; }}
</style>
</head>
<body>
<h1>🔒 GSC Audit Report{' — ' + project if project else ''}</h1>
<p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')} | {total} findings</p>

<div class="summary">
  <div class="card CRITICAL"><div class="num">{crit}</div>Critical</div>
  <div class="card HIGH"><div class="num">{high}</div>High</div>
  <div class="card MEDIUM"><div class="num">{medium}</div>Medium</div>
  <div class="card TOTAL"><div class="num">{total}</div>Total</div>
</div>

<h2>Findings</h2>
"""
    for f in findings:
        detail = (f['detail'] or '')[:200]
        html += f"""<div class="finding {f['category']}">
  <span class="badge badge-{f['category']}">{f['category']}</span>
  <span class="title">{f['title']}</span>
  <div class="meta">{f['file_path'] or '?'}:{f['line_number'] or '?'} | Status: {f['status'] or 'open'}</div>
  <div class="detail">{detail}</div>
</div>
"""

    html += """<footer>Generated by GSC — <a href="https://github.com/poliakarmai/gsc">github.com/poliakarmai/gsc</a></footer>
</body></html>"""

    out = output or f"/tmp/gsc_report_{project or 'all'}.html"
    with open(out, 'w') as f:
        f.write(html)
    print(f"✅ Report: {out} ({len(html)} bytes) -> open {out}")

if __name__ == "__main__":
    project = sys.argv[1] if len(sys.argv) > 1 else None
    output = sys.argv[2] if len(sys.argv) > 2 else None
    export_html(project, output)
